###############################################################################
# buildspec-frontend.yml
# CodeBuild spec: install → build React → sync to S3 → invalidate CloudFront
###############################################################################
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Node dependencies..."
      - cd frontend && npm ci

  pre_build:
    commands:
      - echo "Setting API base URL..."
      - echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" > .env

  build:
    commands:
      - echo "Building React app..."
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo "Syncing to S3 bucket $FRONTEND_BUCKET..."
      - |
        aws s3 sync frontend/dist/ "s3://$FRONTEND_BUCKET/" \
          --delete \
          --cache-control "max-age=31536000,public" \
          --exclude "index.html"
      - |
        aws s3 cp frontend/dist/index.html "s3://$FRONTEND_BUCKET/index.html" \
          --cache-control "no-cache,no-store,must-revalidate"
      - echo "Invalidating CloudFront cache..."
      - |
        aws cloudfront create-invalidation \
          --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
          --paths "/*"
      - echo "Frontend deployment complete!"

artifacts:
  files:
    - frontend/dist/**/*
  name: frontend_artifact

cache:
  paths:
    - frontend/node_modules/**/*
